name: Linux Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DENABLE_SANITIZER_ADDRESS=ON -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON
      - name: Build project
        run: |
          cd build
          cmake --build . --config Debug
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --build-config Debug
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -x gcov-8 || echo "Codecov did not collect coverage reports"
  clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITIZER_ADDRESS=ON -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON
      - name: Build project
        run: |
          cd build
          cmake --build . --config Debug
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --build-config Debug
