name: Linux Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  gcc-10:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install g++-10
        run: |
          sudo apt-get install g++-10
      - name: Install Conan
        run: |
          python3 -m pip install --upgrade pip
          pip3 install conan
      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DENABLE_SANITIZER_ADDRESS=ON -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON
      - name: Build project
        run: |
          cd build
          cmake --build . --config Debug
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --build-config Debug
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -x gcov-10 || echo "Codecov did not collect coverage reports"
