name: Linux Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DENABLE_COVERAGE=ON
      - name: Build project
        run: |
          cd build
          cmake --build .
      - name: Run tests
        run: |
          cd build
          ctest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
