name: MacOs Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  apple-clang:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
      - name: Build project
        run: |
          cd build
          cmake --build . --config Debug
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --build-config Debug
